Models/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace _1670Project.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Type { get; set; }
    }

}

Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _1670Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace _1670Project.Controllers
{
    public class GenresController : Controller
    {
        private readonly BookStoreContext _context;

        public GenresController(BookStoreContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
              return _context.Genre != null ? 
                          View(await _context.Genre.ToListAsync()) :
                          Problem("Entity set 'BookStoreContext.Genre'  is null.");
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [Authorize]
        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }


        [Authorize]
        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }
        [Authorize]
        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        [Authorize]
        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }
        [Authorize]
        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genre == null)
            {
                return Problem("Entity set 'BookStoreContext.Genre'  is null.");
            }
            var genre = await _context.Genre.FindAsync(id);
            if (genre != null)
            {
                _context.Genre.Remove(genre);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
          return (_context.Genre?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Genres/Create.cshtml
@model _1670Project.Models.Genre

@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-4">
        <h4 class="pb-10">Genre</h4>
        <form asp-action="Create" class="w-40">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="input-container">
                <label asp-for="Type" class="w-40"></label>
                <input asp-for="Type" class="input" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="input-container">
                <input type="submit" value="Create" class="btn btn-sec" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger">Back to List</a>
</div>

Views/Genres/Delete.cshtml
@model _1670Project.Models.Genre

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="w-40">
        <h2 class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </h2>
        <h3 class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </h3>
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <a class="btn btn-danger" asp-controller="Genres" asp-action="Index">List Genres</a>
            <input type="submit" value="Delete" class="btn btn-sec" />
        </div>
    </form>
</div>

Views/Genres/Edit.cshtml
@model _1670Project.Models.Genre

@{
    ViewData["Title"] = "Edit";
}
        <form asp-action="Edit" class="w-40">
            <h4>Edit Genre</h4>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="input-container">
                 <label asp-for="Type" class="w-40"></label>
                 <input asp-for="Type" class="input" />
                 <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-danger">Back</a>
                <input type="submit" value="Save" class="btn btn-sec" />
            </div>
        </form>

Views/Genres/Index.cshtml
@model IEnumerable<_1670Project.Models.Genre>

@{
    ViewData["Title"] = "Index";
}
<p>
    <a asp-action="Create" class="btn btn-sec">Create New</a>
</p>
<table class="table tableManager">
    <thead>
    <th>Type</th>
    <th>Actions</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>